### ISSUE TITLE
Some channels missing from the website

### ISSUE THREAD

**Issue by dwightwatson** [laravel-notification-channels/website#1]
While searching today I came across the `facebook-poster` channel which I hadn't seen before, because it's not listed on the website. I wonder if perhaps there are other channels going unnoticed because they aren't actually listed on the site.

Is there a way we could automatically sync the available channels and the website? Might be able to learn and/or collaborate with the Laravel Socialite providers team.

**Comment by atymic** [comment]
I plan to re-do the website soon, as it's pretty janky at the moment.

I'm currently in the process of auditing all the channels:
https://github.com/laravel-notification-channels/laravel-notification-channels.github.io/issues/18

Just waiting for L6 support to be tagged and merged and i'll add it.

There are a couple of others missing as well, but I'm waiting for them to be up to date before adding them.

This repo isn't actually the main one for the site, I'm in the process of moving it from GH pages to netlify.

The old repo is here:
https://github.com/laravel-notification-channels/laravel-notification-channels.github.io

**Comment by dwightwatson** [comment]
Ah, awesome to hear - excited about the prospect of an audit and cleanup.

**Comment by atymic** [comment]
Yep, i'm through most of the channels. There are a couple which have got <30 downloads in > 3 years, so might be worth deprecating plus a bunch where i'm waiting for maintainers.

**Comment by atymic** [comment]
Hey @dwightwatson 

I'm pretty sure we're all up to date now. I've built and deployed the new website as well :)

I'm going to close this now, but feel free to ping me if there's anything else missing.

**Comment by dwightwatson** [comment]
New site looks great!

**Comment by atymic** [comment]
Thanks :)

PRs are welcome if you notice any issues.
