### ISSUE TITLE
New Logo?

### ISSUE THREAD

**Issue by irazasyed** [laravel-notification-channels/website#5]
The current logo on the website looks very blurry on a retina display beside it's using Laravel's old logo.

I think it's about time it gets some attention too.

I can share a few concepts based on the existing logo but using Laravel's new logo and high quality as well. Let me know if it interests you!

**Comment by irazasyed** [comment]
![Rounded-Black](https://user-images.githubusercontent.com/1915268/67271462-31600380-f4d8-11e9-9143-18e197b26f48.png)

**Comment by irazasyed** [comment]
![Rounded-Black-1](https://user-images.githubusercontent.com/1915268/67271559-5ce2ee00-f4d8-11e9-81ce-faba29f09724.png)

**Comment by irazasyed** [comment]
![Red](https://user-images.githubusercontent.com/1915268/67271712-b77c4a00-f4d8-11e9-85d1-ea6875a06903.png)

**Comment by irazasyed** [comment]
![Gradient](https://user-images.githubusercontent.com/1915268/67272248-d3342000-f4d9-11e9-86ba-6933108766e0.png)

**Comment by irazasyed** [comment]
![Gradient-2](https://user-images.githubusercontent.com/1915268/67272392-142c3480-f4da-11e9-81f1-5bd5da1e2c5f.png)

**Comment by irazasyed** [comment]
![Square](https://user-images.githubusercontent.com/1915268/67272496-463d9680-f4da-11e9-836c-5a2ebb98bbbd.png)

**Comment by irazasyed** [comment]
That's all. I quickly created them. If it doesn't interest you / the core team. Feel free to close this but if you like one of them, please use reactions to vote and I'll send over the final copy accordingly.

**Comment by atymic** [comment]
Looks good! Thanks for doing these :)

I like the first one, only suggestion I'd make is a bit less border radius?

![image](https://user-images.githubusercontent.com/50683531/67276971-7fddc400-f511-11e9-8e68-8df86385cfc8.png)

**Comment by atymic** [comment]
BTW, what do you think of the new site? 😃

**Comment by irazasyed** [comment]
Sure, we can do that. I was using an iOS App icon template actually. Hence, the high radius.

# 1

![Light-Radius](https://user-images.githubusercontent.com/1915268/67277974-979f5300-f4e5-11e9-8bfd-5bdee034b345.png)

# 2

![Light-Radius-2](https://user-images.githubusercontent.com/1915268/67277995-a4bc4200-f4e5-11e9-9516-f29c16697cbe.png)


Tell me if we need to improve more / less ?

**Comment by irazasyed** [comment]
> BTW, what do you think of the new site? 😃

Oh, I think it's fantastic. The revamp was much needed. It looks clean and easy on the eyes too (and smooth). Good job 👍 

Is there a dark-mode, tho? That would make this awesome.

**Comment by atymic** [comment]
I think the second one looks great :)

> Is there a dark-mode, tho? That would make this awesome.

I'll look into that, not sure if vuepress has support for it.

**Comment by irazasyed** [comment]
Here's the SVG file: https://cl.ly/dbba3b7378de

> I'll look into that, not sure if vuepress has support for it.

Sounds good.

Let me know if you need it in any other format?

**Comment by atymic** [comment]
That's fine, i'll create a PR tomorrow. Thanks again!

**Comment by irazasyed** [comment]
Cool. Here's PNG (It's already been compressed too but feel free to optimize more): https://cl.ly/cb5ccda43d90

Might as well update the org. profile image with it :)

Thanks!
