### ISSUE TITLE
Documentation not updating

### ISSUE THREAD

**Issue by irazasyed** [laravel-notification-channels/website#52]
Looks like the scheduled builds got disabled due to which the site is not getting updated with new changes.

<img width="900" alt="Documentation" src="https://user-images.githubusercontent.com/1915268/140324401-846986b9-b377-441b-baeb-b9b8797eb7e2.png">

Please check and update.

**Comment by irazasyed** [comment]
@atymic Could you please take a look at this, if possible? Thanks!

**Comment by atymic** [comment]
Merged a dependabot pr to fix :)

**Comment by irazasyed** [comment]
Thanks

**Comment by irazasyed** [comment]
@atymic It doesn't seem to be working as I don't see my updates to the docs reflected on the site and it has not triggered the builds either. Please take a look when you get a chance. Thank you!

**Comment by atymic** [comment]
I can see the build ran nov 14
<img width="643" alt="Screen Shot 2021-11-29 at 11 19 12@2x" src="https://user-images.githubusercontent.com/50683531/143792297-55859ca9-8b8e-4df3-a920-d8f99e904459.png">

**Comment by atymic** [comment]
Ok fixed now :) sorry

**Comment by irazasyed** [comment]
Works now. Thanks :)
